### ISSUE TITLE
Add SITL options that can be passed to the dronekit runner to Readme/help

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/dronekit-sitl-runner#12]
If you run ``dronekit-sitl`` or ``dronekit-sitl --help`` you get the following options:
```
ubuntu@ubuntu:~$ dronekit-sitl 
Please specify one of:
  dronekit-sitl --list
  dronekit-sitl --reset
  dronekit-sitl <copter(-version)>
  dronekit-sitl <plane(-version)>
```

However I can see from your example I can actually specify more options (model, home, IO, s):
```
dronekit-sitl copter-3.4-dev -I0 -S --model quad --home=-35.363261,149.165230,584,353
```
Is there a list of all options we can pass anywhere?

The help above and the readme.md should make it clear that there are additional commands that can be supported.

**Comment by TShapinsky** [comment]
Everything after the copter or plane version is passed to ArduPilot. You can get a list of parameters by running `./Ardu<Copter/Plane> -h`

**Comment by hamishwillee** [comment]
@TShapinsky Thanks. The readme and help should say that :-)

**Comment by TShapinsky** [comment]
@hamishwillee because dronekit-sitl passes through all the arguments to Ardu<Copter/Plane> if you ran `dronekit-sitl copter-3.4-dev -h` it should give you a list of parameters because the available parameters change between different versions of Ardu<Copter/Plane>

**Comment by hamishwillee** [comment]
Thanks very much. Closing this (have updated #17 appropriately)
